/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence1)
#  Generated on:      Sun Mar  8 16:11:08 2026
#  Design:            password_lock_system
#  Command:           saveNetlist pd_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  8 2026 16:06:43 IST (Mar  8 2026 10:36:43 UTC)
// Verification Directory fv/password_lock_system 
module password_attempt_counter (
	clk, 
	enter, 
	correct, 
	rstn, 
	cnt, 
	access, 
	alarm);
   input clk;
   input enter;
   input correct;
   input rstn;
   output [1:0] cnt;
   output access;
   output alarm;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;

   DFFRHQX1 \cnt_reg[1]  (.CK(clk),
	.D(n_5),
	.Q(cnt[1]),
	.RN(rstn));
   SDFFRHQX1 \cnt_reg[0]  (.CK(clk),
	.D(cnt[0]),
	.Q(cnt[0]),
	.RN(rstn),
	.SE(enter),
	.SI(n_3));
   SDFFRHQX1 alarm_reg (.CK(clk),
	.D(alarm),
	.Q(alarm),
	.RN(rstn),
	.SE(enter),
	.SI(n_1));
   OAI22XL g333__2398 (.A0(correct),
	.A1(n_4),
	.B0(enter),
	.B1(n_0),
	.Y(n_5));
   SDFFSHQX1 access_reg (.CK(clk),
	.D(access),
	.Q(access),
	.SE(enter),
	.SI(correct),
	.SN(rstn));
   AOI21XL g335__5107 (.A0(cnt[0]),
	.A1(enter),
	.B0(cnt[1]),
	.Y(n_4));
   OAI21XL g336__6260 (.A0(cnt[0]),
	.A1(correct),
	.B0(n_2),
	.Y(n_3));
   INVX1 g337 (.A(n_1),
	.Y(n_2));
   NOR2XL g338__4319 (.A(n_0),
	.B(correct),
	.Y(n_1));
   INVX1 g341 (.A(cnt[1]),
	.Y(n_0));
endmodule

module password_lock_system (
	reset, 
	clk, 
	passin, 
	newpass, 
	enter, 
	chg_pass, 
	access, 
	alarm, 
	count);
   input reset;
   input clk;
   input [15:0] passin;
   input [15:0] newpass;
   input enter;
   input chg_pass;
   output access;
   output alarm;
   output [1:0] count;

   // Internal wires
   wire [15:0] current_password;
   wire is_correct;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;

   password_attempt_counter counter (.clk(clk),
	.enter(enter),
	.correct(is_correct),
	.rstn(reset),
	.cnt(count),
	.access(access),
	.alarm(alarm));
   OAI31X1 g1307__8428 (.A0(n_24),
	.A1(n_23),
	.A2(n_25),
	.B0(n_29),
	.Y(is_correct));
   NAND4XL g1308__5526 (.A(n_28),
	.B(passin[0]),
	.C(passin[2]),
	.D(passin[15]),
	.Y(n_29));
   NOR4BBX1 g1309__6783 (.AN(passin[3]),
	.BN(n_27),
	.C(passin[1]),
	.D(passin[4]),
	.Y(n_28));
   NOR4BX1 g1310__3680 (.AN(passin[6]),
	.B(passin[5]),
	.C(passin[12]),
	.D(n_26),
	.Y(n_27));
   NAND4XL g1311__1617 (.A(n_20),
	.B(passin[7]),
	.C(passin[8]),
	.D(passin[9]),
	.Y(n_26));
   NAND4XL g1312__2802 (.A(n_22),
	.B(n_15),
	.C(n_14),
	.D(n_21),
	.Y(n_25));
   NAND4XL g1313__1705 (.A(n_12),
	.B(n_18),
	.C(n_13),
	.D(n_7),
	.Y(n_24));
   NAND4XL g1314__5122 (.A(n_5),
	.B(n_6),
	.C(n_8),
	.D(n_9),
	.Y(n_23));
   NOR4X1 g1315__8246 (.A(n_4),
	.B(n_17),
	.C(n_16),
	.D(n_19),
	.Y(n_22));
   NOR2XL g1316__7098 (.A(n_10),
	.B(n_11),
	.Y(n_21));
   NOR4BBX1 g1317__6131 (.AN(passin[13]),
	.BN(passin[11]),
	.C(passin[10]),
	.D(passin[14]),
	.Y(n_20));
   XOR2XL g1318__1881 (.A(current_password[10]),
	.B(passin[10]),
	.Y(n_19));
   OAI21X1 g1319__5115 (.A0(current_password[5]),
	.A1(passin[5]),
	.B0(n_2),
	.Y(n_18));
   AOI21X1 g1320__7482 (.A0(current_password[11]),
	.A1(passin[11]),
	.B0(n_1),
	.Y(n_17));
   XOR2XL g1321__4733 (.A(current_password[8]),
	.B(passin[8]),
	.Y(n_16));
   OAI21XL g1322__6161 (.A0(current_password[3]),
	.A1(passin[3]),
	.B0(n_3),
	.Y(n_15));
   XNOR2XL g1323__9315 (.A(current_password[2]),
	.B(passin[2]),
	.Y(n_14));
   XNOR2XL g1324__9945 (.A(current_password[7]),
	.B(passin[7]),
	.Y(n_13));
   XNOR2XL g1325__2883 (.A(current_password[4]),
	.B(passin[4]),
	.Y(n_12));
   XOR2XL g1326__2346 (.A(current_password[1]),
	.B(passin[1]),
	.Y(n_11));
   XOR2XL g1327__1666 (.A(current_password[0]),
	.B(passin[0]),
	.Y(n_10));
   XNOR2XL g1328__7410 (.A(current_password[12]),
	.B(passin[12]),
	.Y(n_9));
   XNOR2XL g1329__6417 (.A(current_password[13]),
	.B(passin[13]),
	.Y(n_8));
   XNOR2XL g1330__5477 (.A(current_password[6]),
	.B(passin[6]),
	.Y(n_7));
   XNOR2XL g1331__2398 (.A(current_password[14]),
	.B(passin[14]),
	.Y(n_6));
   XNOR2XL g1332__5107 (.A(current_password[15]),
	.B(passin[15]),
	.Y(n_5));
   XOR2XL g1333__6260 (.A(current_password[9]),
	.B(passin[9]),
	.Y(n_4));
   NAND2XL g1334__4319 (.A(passin[3]),
	.B(current_password[3]),
	.Y(n_3));
   NAND2XL g1335__8428 (.A(passin[5]),
	.B(current_password[5]),
	.Y(n_2));
   NOR2XL g1336__5526 (.A(current_password[11]),
	.B(passin[11]),
	.Y(n_1));
   SDFFSHQX1 \current_password_reg[12]  (.CK(clk),
	.D(newpass[12]),
	.Q(current_password[12]),
	.SE(n_0),
	.SI(current_password[12]),
	.SN(reset));
   SDFFSHQX1 \current_password_reg[4]  (.CK(clk),
	.D(newpass[4]),
	.Q(current_password[4]),
	.SE(n_0),
	.SI(current_password[4]),
	.SN(reset));
   SDFFSHQX1 \current_password_reg[5]  (.CK(clk),
	.D(newpass[5]),
	.Q(current_password[5]),
	.SE(n_0),
	.SI(current_password[5]),
	.SN(reset));
   SDFFSHQX1 \current_password_reg[9]  (.CK(clk),
	.D(newpass[9]),
	.Q(current_password[9]),
	.SE(n_0),
	.SI(current_password[9]),
	.SN(reset));
   SDFFSHQX1 \current_password_reg[2]  (.CK(clk),
	.D(newpass[2]),
	.Q(current_password[2]),
	.SE(n_0),
	.SI(current_password[2]),
	.SN(reset));
   SDFFRHQX1 \current_password_reg[0]  (.CK(clk),
	.D(newpass[0]),
	.Q(current_password[0]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[0]));
   SDFFRHQX1 \current_password_reg[3]  (.CK(clk),
	.D(newpass[3]),
	.Q(current_password[3]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[3]));
   SDFFRHQX1 \current_password_reg[7]  (.CK(clk),
	.D(newpass[7]),
	.Q(current_password[7]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[7]));
   SDFFRHQX1 \current_password_reg[10]  (.CK(clk),
	.D(newpass[10]),
	.Q(current_password[10]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[10]));
   SDFFRHQX1 \current_password_reg[8]  (.CK(clk),
	.D(newpass[8]),
	.Q(current_password[8]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[8]));
   SDFFRHQX1 \current_password_reg[1]  (.CK(clk),
	.D(newpass[1]),
	.Q(current_password[1]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[1]));
   SDFFRHQX1 \current_password_reg[11]  (.CK(clk),
	.D(newpass[11]),
	.Q(current_password[11]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[11]));
   SDFFRHQX1 \current_password_reg[6]  (.CK(clk),
	.D(newpass[6]),
	.Q(current_password[6]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[6]));
   SDFFRHQX1 \current_password_reg[13]  (.CK(clk),
	.D(newpass[13]),
	.Q(current_password[13]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[13]));
   SDFFRHQX1 \current_password_reg[14]  (.CK(clk),
	.D(newpass[14]),
	.Q(current_password[14]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[14]));
   SDFFRHQX1 \current_password_reg[15]  (.CK(clk),
	.D(newpass[15]),
	.Q(current_password[15]),
	.RN(reset),
	.SE(n_0),
	.SI(current_password[15]));
   NAND2X2 g521__6783 (.A(is_correct),
	.B(chg_pass),
	.Y(n_0));
endmodule

