
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  8 2026 16:06:43 IST (Mar  8 2026 10:36:43 UTC)

// Verification Directory fv/password_lock_system 

module password_attempt_counter(clk, enter, correct, rstn, cnt, access,
     alarm);
  input clk, enter, correct, rstn;
  output [1:0] cnt;
  output access, alarm;
  wire clk, enter, correct, rstn;
  wire [1:0] cnt;
  wire access, alarm;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  DFFRHQX1 \cnt_reg[1] (.RN (rstn), .CK (clk), .D (n_5), .Q (cnt[1]));
  SDFFRHQX1 \cnt_reg[0] (.RN (rstn), .CK (clk), .D (cnt[0]), .SI (n_3),
       .SE (enter), .Q (cnt[0]));
  SDFFRHQX1 alarm_reg(.RN (rstn), .CK (clk), .D (alarm), .SI (n_1), .SE
       (enter), .Q (alarm));
  OAI22XL g333__2398(.A0 (correct), .A1 (n_4), .B0 (enter), .B1 (n_0),
       .Y (n_5));
  SDFFSHQX1 access_reg(.SN (rstn), .CK (clk), .D (access), .SI
       (correct), .SE (enter), .Q (access));
  AOI21XL g335__5107(.A0 (cnt[0]), .A1 (enter), .B0 (cnt[1]), .Y (n_4));
  OAI21XL g336__6260(.A0 (cnt[0]), .A1 (correct), .B0 (n_2), .Y (n_3));
  INVX1 g337(.A (n_1), .Y (n_2));
  NOR2XL g338__4319(.A (n_0), .B (correct), .Y (n_1));
  INVX1 g341(.A (cnt[1]), .Y (n_0));
endmodule

module password_lock_system(reset, clk, passin, newpass, enter,
     chg_pass, access, alarm, count);
  input reset, clk, enter, chg_pass;
  input [15:0] passin, newpass;
  output access, alarm;
  output [1:0] count;
  wire reset, clk, enter, chg_pass;
  wire [15:0] passin, newpass;
  wire access, alarm;
  wire [1:0] count;
  wire [15:0] current_password;
  wire is_correct, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  password_attempt_counter counter(.clk (clk), .enter (enter), .correct
       (is_correct), .rstn (reset), .cnt (count), .access (access),
       .alarm (alarm));
  OAI31X1 g1307__8428(.A0 (n_24), .A1 (n_23), .A2 (n_25), .B0 (n_29),
       .Y (is_correct));
  NAND4XL g1308__5526(.A (n_28), .B (passin[0]), .C (passin[2]), .D
       (passin[15]), .Y (n_29));
  NOR4BBX1 g1309__6783(.AN (passin[3]), .BN (n_27), .C (passin[1]), .D
       (passin[4]), .Y (n_28));
  NOR4BX1 g1310__3680(.AN (passin[6]), .B (passin[5]), .C (passin[12]),
       .D (n_26), .Y (n_27));
  NAND4XL g1311__1617(.A (n_20), .B (passin[7]), .C (passin[8]), .D
       (passin[9]), .Y (n_26));
  NAND4XL g1312__2802(.A (n_22), .B (n_15), .C (n_14), .D (n_21), .Y
       (n_25));
  NAND4XL g1313__1705(.A (n_12), .B (n_18), .C (n_13), .D (n_7), .Y
       (n_24));
  NAND4XL g1314__5122(.A (n_5), .B (n_6), .C (n_8), .D (n_9), .Y
       (n_23));
  NOR4X1 g1315__8246(.A (n_4), .B (n_17), .C (n_16), .D (n_19), .Y
       (n_22));
  NOR2XL g1316__7098(.A (n_10), .B (n_11), .Y (n_21));
  NOR4BBX1 g1317__6131(.AN (passin[13]), .BN (passin[11]), .C
       (passin[10]), .D (passin[14]), .Y (n_20));
  XOR2XL g1318__1881(.A (current_password[10]), .B (passin[10]), .Y
       (n_19));
  OAI21X1 g1319__5115(.A0 (current_password[5]), .A1 (passin[5]), .B0
       (n_2), .Y (n_18));
  AOI21X1 g1320__7482(.A0 (current_password[11]), .A1 (passin[11]), .B0
       (n_1), .Y (n_17));
  XOR2XL g1321__4733(.A (current_password[8]), .B (passin[8]), .Y
       (n_16));
  OAI21XL g1322__6161(.A0 (current_password[3]), .A1 (passin[3]), .B0
       (n_3), .Y (n_15));
  XNOR2XL g1323__9315(.A (current_password[2]), .B (passin[2]), .Y
       (n_14));
  XNOR2XL g1324__9945(.A (current_password[7]), .B (passin[7]), .Y
       (n_13));
  XNOR2XL g1325__2883(.A (current_password[4]), .B (passin[4]), .Y
       (n_12));
  XOR2XL g1326__2346(.A (current_password[1]), .B (passin[1]), .Y
       (n_11));
  XOR2XL g1327__1666(.A (current_password[0]), .B (passin[0]), .Y
       (n_10));
  XNOR2XL g1328__7410(.A (current_password[12]), .B (passin[12]), .Y
       (n_9));
  XNOR2XL g1329__6417(.A (current_password[13]), .B (passin[13]), .Y
       (n_8));
  XNOR2XL g1330__5477(.A (current_password[6]), .B (passin[6]), .Y
       (n_7));
  XNOR2XL g1331__2398(.A (current_password[14]), .B (passin[14]), .Y
       (n_6));
  XNOR2XL g1332__5107(.A (current_password[15]), .B (passin[15]), .Y
       (n_5));
  XOR2XL g1333__6260(.A (current_password[9]), .B (passin[9]), .Y
       (n_4));
  NAND2XL g1334__4319(.A (passin[3]), .B (current_password[3]), .Y
       (n_3));
  NAND2XL g1335__8428(.A (passin[5]), .B (current_password[5]), .Y
       (n_2));
  NOR2XL g1336__5526(.A (current_password[11]), .B (passin[11]), .Y
       (n_1));
  SDFFSHQX1 \current_password_reg[12] (.SN (reset), .CK (clk), .D
       (newpass[12]), .SI (current_password[12]), .SE (n_0), .Q
       (current_password[12]));
  SDFFSHQX1 \current_password_reg[4] (.SN (reset), .CK (clk), .D
       (newpass[4]), .SI (current_password[4]), .SE (n_0), .Q
       (current_password[4]));
  SDFFSHQX1 \current_password_reg[5] (.SN (reset), .CK (clk), .D
       (newpass[5]), .SI (current_password[5]), .SE (n_0), .Q
       (current_password[5]));
  SDFFSHQX1 \current_password_reg[9] (.SN (reset), .CK (clk), .D
       (newpass[9]), .SI (current_password[9]), .SE (n_0), .Q
       (current_password[9]));
  SDFFSHQX1 \current_password_reg[2] (.SN (reset), .CK (clk), .D
       (newpass[2]), .SI (current_password[2]), .SE (n_0), .Q
       (current_password[2]));
  SDFFRHQX1 \current_password_reg[0] (.RN (reset), .CK (clk), .D
       (newpass[0]), .SI (current_password[0]), .SE (n_0), .Q
       (current_password[0]));
  SDFFRHQX1 \current_password_reg[3] (.RN (reset), .CK (clk), .D
       (newpass[3]), .SI (current_password[3]), .SE (n_0), .Q
       (current_password[3]));
  SDFFRHQX1 \current_password_reg[7] (.RN (reset), .CK (clk), .D
       (newpass[7]), .SI (current_password[7]), .SE (n_0), .Q
       (current_password[7]));
  SDFFRHQX1 \current_password_reg[10] (.RN (reset), .CK (clk), .D
       (newpass[10]), .SI (current_password[10]), .SE (n_0), .Q
       (current_password[10]));
  SDFFRHQX1 \current_password_reg[8] (.RN (reset), .CK (clk), .D
       (newpass[8]), .SI (current_password[8]), .SE (n_0), .Q
       (current_password[8]));
  SDFFRHQX1 \current_password_reg[1] (.RN (reset), .CK (clk), .D
       (newpass[1]), .SI (current_password[1]), .SE (n_0), .Q
       (current_password[1]));
  SDFFRHQX1 \current_password_reg[11] (.RN (reset), .CK (clk), .D
       (newpass[11]), .SI (current_password[11]), .SE (n_0), .Q
       (current_password[11]));
  SDFFRHQX1 \current_password_reg[6] (.RN (reset), .CK (clk), .D
       (newpass[6]), .SI (current_password[6]), .SE (n_0), .Q
       (current_password[6]));
  SDFFRHQX1 \current_password_reg[13] (.RN (reset), .CK (clk), .D
       (newpass[13]), .SI (current_password[13]), .SE (n_0), .Q
       (current_password[13]));
  SDFFRHQX1 \current_password_reg[14] (.RN (reset), .CK (clk), .D
       (newpass[14]), .SI (current_password[14]), .SE (n_0), .Q
       (current_password[14]));
  SDFFRHQX1 \current_password_reg[15] (.RN (reset), .CK (clk), .D
       (newpass[15]), .SI (current_password[15]), .SE (n_0), .Q
       (current_password[15]));
  NAND2XL g521__6783(.A (is_correct), .B (chg_pass), .Y (n_0));
endmodule

